---
title: "Difference in differences analysis"
output: html_notebook
---


# TODO: 

- [x] Add robust standard errors for all models
- [x] Check stargazer output

```{r load libraries, warning=F}
library(data.table)
library(stargazer)
library(magrittr)
library(sandwich)
library(lmtest)
```

```{r load data}
load('../data/processed/survey_data_clean_20220410.RData')
d <- data.table(x)
```

```{r}
d
```


```{r}
# Remove the ones that have no Q12 data (missing data)
d <- d[q12.score != 0,]

# TODO: check this (attrition?). Limit the results to answers that have something for Q25
d[q25.score == 0, ]
d[is.na(posttask.time),]
# These two above are *not* the same, I'm gonna keep the ones that are finished (2/7). The other 5/7 have no time spent in Q25 so we're good removing those.
d <- d[!is.na(posttask.time),]
```

```{r} 
getDIDModel <- function(subset_groups  = c('positive', 'control')) {
	d1 <- d[treatment %in% subset_groups, ]
	d1.q1  <- d1[, .(treatment, score=q12.score, time=0)]
	d1.q25 <- d1[, .(treatment, score=q25.score, time=1)]
	d1.both <- rbind(d1.q1, d1.q25)
	return(d1.both[, lm(score ~ time + treatment + time*treatment)])
}
```


## 1. Estimate the simple (short) DID model

```{r 1.1 Positive vs Control}
# 1.1 Positive vs Control
m1.1 <- getDIDModel(c('positive', 'control'))
summary(m1.1)
```


```{r 1.2 Neutral vs Control}
# 1.2 Neutral vs Control
m1.2 <- getDIDModel(c('neutral', 'control'))
summary(m1.2)
```


```{r 1.3 Negative vs Control}
# 1.3 Negative vs Control
m1.3 <- getDIDModel(c('negative', 'control'))
summary(m1.3)
stargazer(m1.1, m1.3, m1.2, type='text',
		  dep.var.labels = 'Score (correct words remembered)',
		  column.labels = c('Positive', 'Negative', 'Neutral'),
		  title="Table 1. Score (correct words remembered) DID estimation",
		  se=list(m3.1$rse, m3.2$rse, m3.3$rse),
		  omit="^(time|treatmentpositive|treatmentnegative|treatmentneutral)$",
		  covariate.labels=c(
		  	'Time',
		  	'DID estimator (positive)',
		  	'DID estimator (negative)',
		  	'DID estimator (neutral)'
		  ),
		  header=F
		  )
```

## 2. Blocked model

```{r}
getBlockedModel <- function(subset_groups = c('control', 'positive')) {
	d1 <- d[treatment %in% subset_groups, ]
	d1.q1  <- d1[, .(treatment, age.demographic, score=q12.score, time=0)]
	d1.q25 <- d1[, .(treatment, age.demographic, score=q25.score, time=1)]
	d1.both <- rbind(d1.q1, d1.q25)
	return(d1.both[, lm(score ~ time*treatment + age.demographic)])
}
```

```{r 2. Run the block models}
m2.1 <- getBlockedModel(c('control', 'positive'))
m2.2 <- getBlockedModel(c('control', 'neutral'))
m2.3 <- getBlockedModel(c('control', 'negative'))
stargazer(m2.1, m2.2, m2.3, type='text')
```


## 3. Covariate (long) model

```{r}
dd <- tidyr::gather(d, time, score, q12.score:q25.score)
dd$time <- ifelse(dd$time == 'q12.score', 0, 1)
dd <- data.table(dd)
```

```{r}
m3.1 <- dd[treatment %in% c('control', 'positive'), lm(score ~ time*treatment + highest.education + english.native)]
m3.1$rse <- sqrt(diag(vcovHC(m3.1)))
m3.2 <- dd[treatment %in% c('control', 'negative'), lm(score ~ time*treatment + highest.education + english.native)]
m3.2$rse <- sqrt(diag(vcovHC(m3.2)))
m3.3 <- dd[treatment %in% c('control', 'neutral'),  lm(score ~ time*treatment + highest.education + english.native)]
m3.3$rse <- sqrt(diag(vcovHC(m3.3)))
stargazer(m3.1, m3.2, m3.3, type='text',
		  dep.var.labels = 'Score (correct words remembered)',
		  column.labels = c('Positive', 'Negative', 'Neutral'),
		  title="Table 2. Score (correct words remembered) DID estimation (covariated model)",
		  se=list(m3.1$rse, m3.2$rse, m3.3$rse),
		  omit="^(time|treatmentpositive|treatmentnegative|treatmentneutral)$|Other",
		  covariate.labels=c(
		  	'Bachelor\'s degree',
		  	'High school diploma',
		  	'Master\'s Degree',
		  	'PhD/MD/JD',
		  	'English as native language',
		  	'DID estimator (positive)',
		  	'DID estimator (negative)',
		  	'DID estimator (neutral)'
		  ),
		  header=F
		  )
```



$$
\text{Score} = \beta_0 + \beta_1\text{time} + \beta_2\text{treatment} + \beta_3\text{time}*\text{treatment} + \beta_6 \text{highest_education} + \beta_5 \text{english native} + \epsilon
$$

--- 

# Run on time outcome variable

```{r}
getShortTimeModel <- function(subset_groups = c('positive', 'control')) {
	d1 <- d[treatment %in% subset_groups, ]
	d1.pretask  <- d1[, .(treatment, Y=pretask.time, time=0)]
	d1.posttask <- d1[, .(treatment, Y=posttask.time, time=1)]
	d1.both <- rbind(d1.pretask, d1.posttask)
	return(d1.both[, lm(Y ~ time*treatment)])
}
```

```{r Short time model}
m50.1 <- ddx[treatment %in% c('control', 'positive'), lm(completion.time ~ time*treatment)]
m50.1$rse <- sqrt(diag(vcovHC(m50.1)))
m50.2 <- ddx[treatment %in% c('control', 'negative'), lm(completion.time ~ time*treatment)]
m50.2$rse <- sqrt(diag(vcovHC(m50.2)))
m50.3 <- ddx[treatment %in% c('control', 'neutral'),  lm(completion.time ~ time*treatment)]
m50.3$rse <- sqrt(diag(vcovHC(m50.3)))
stargazer(m50.1, m50.2, m50.3,
		  type='text',
		  dep.var.labels = 'Completion time (secs)',
		  column.labels = c('Positive', 'Negative', 'Neutral'),
		  title="Table 3. Completion time covariated model",
		  se=list(m50.1$rse, m50.2$rse, m50.3$rse),
		  omit="^(time|treatmentpositive|treatmentnegative|treatmentneutral)$",
		  covariate.labels=c(
		  	'DID estimator (positive)',
		  	'DID estimator (negative)',
		  	'DID estimator (neutral)'
		  ),
		  header=F
  )
```


## Run longer model

```{r}
getLongTimeModel <- function(subset_groups = c('positive', 'control')) {
	d1 <- d[treatment %in% subset_groups, ]
	d1.pretask  <- d1[, .(treatment, Y=pretask.time, time=0, age.demographic)]
	d1.posttask <- d1[, .(treatment, Y=posttask.time, time=1, age.demographic)]
	d1.both <- rbind(d1.pretask, d1.posttask)
	return(d1.both[, lm(Y ~ time*treatment + age.demographic)])
}
dd[]
```



```{r Long time model}
ddx <- tidyr::gather(d, time, completion.time, pretask.time:posttask.time)
ddx$time <- ifelse(ddx$time == 'pretask.time', 0, 1)
ddx <- data.table(ddx)
m53.1 <- ddx[treatment %in% c('control', 'positive'), lm(completion.time ~ time*treatment + highest.education + english.native)]
m53.1$rse <- sqrt(diag(vcovHC(m53.1)))
m53.2 <- ddx[treatment %in% c('control', 'negative'), lm(completion.time ~ time*treatment + highest.education + english.native)]
m53.2$rse <- sqrt(diag(vcovHC(m53.2)))
m53.3 <- ddx[treatment %in% c('control', 'neutral'),  lm(completion.time ~ time*treatment + highest.education + english.native)]
m53.3$rse <- sqrt(diag(vcovHC(m53.3)))
stargazer(m53.1, m53.2, m53.3,
		  type='text',
		  se=list(m53.1$rse, m53.2$rse, m53.3$rse),
#		  covariate.labels = c(),
		  dep.var.labels = 'Completion time (secs)',
		  column.labels = c('Positive', 'Negative', 'Neutral'),
			title="Table 4. Completion time covariated model",
		  omit="^(time|treatmentpositive|treatmentnegative|treatmentneutral)$|Other",
		  covariate.labels=c(
		  	'Bachelor\'s degree',
		  	'High school diploma',
		  	'Master\'s Degree',
		  	'PhD/MD/JD',
		  	'English as native language',
		  	'DID estimator (positive)',
		  	'DID estimator (negative)',
		  	'DID estimator (neutral)'
		  ),
			header=F
		  )

```

