---
title: "exploratory-analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ggplot2)
install.packages("cobalt")
library("cobalt")
library(grid)
library(gridExtra)
install.packages("effectsize")
library(effectsize)
install.packages("WeightIt")
install.packages("mlogit")
library(mlogit)
library("WeightIt")
library(stargazer)
```

```{r}
data = setDT(x)
# Adding a status column of missing, attrition, or completed the test
data[, status := ifelse((q12.score != 0 & q25.score == 0 & finished == 0) | (finished == 1 & q12.score != 0 & q25.score == 0), "attritted", ifelse((q12.score == 0 & q25.score == 0) | (q12.score == 0 & q25.score != 0), "missing_data", "complete"))]
```

**Power Analysis**
```{r}

#Assumption of 10% change in score - estimate was off
power.t.test(n= NULL, delta = 1, sd = 1, sig.level = 0.05, power = 0.8, type = "two.sample", alternative = "one.sided")
#pwr.t.test(n=NULL, d=.1, sig.level=0.05, power=0.8, type="two.sample", alternative="greater")

experiment <- function(treat_mean = 100, control_mean=90, n_per_group=10) {
  treat_group   <- rnorm(n=n_per_group, mean=treat_mean,   sd=10)
  control_group <- rnorm(n=n_per_group, mean=control_mean, sd=10)
  t.test(treat_group, control_group)$p.value
}
mean(replicate(100, experiment(treat_mean = 100, control_mean=90, n_per_group=14)) < 0.05)

#Actual experiment
#see below code chunk for all treatment groups
power.t.test(n=100, delta = 2, sd = 5.14, sig.level = 0.05, power = NULL, type = "two.sample", alternative = "one.sided")

#experiment <- function(treat_mean = 90, control_mean=80, n_per_group=10) {
  #treat_group   <- rnorm(n=n_per_group, mean=treat_mean,   sd=10)
  #control_group <- rnorm(n=n_per_group, mean=control_mean, sd=10)
  #t.test(treat_group, control_group)$p.value
#}
#mean(replicate(100, experiment(treat_mean = 90, control_mean=80, n_per_group=14)) < 0.05)

```

```{r}
data_means <- data[status=='complete', mean(q25.score-q12.score), by=treatment]
data_sd <- data[status=='complete', sd(q25.score-q12.score), by=treatment]

#positive power calc
d_pos <- (data_means[treatment=='positive', V1]-data_means[treatment=='control', V1])

sd_pos <- sd_pooled(data[status=='complete' & treatment=='positive', (q25.score-q12.score)],data[status=='complete' & treatment=='control', (q25.score-q12.score)])

power.t.test(n=29, delta = d_pos, sd = sd_pos, sig.level = 0.05, power = NULL, type = "two.sample", alternative = "one.sided")


#neutral power calc
d_neu <- (data_means[treatment=='neutral', V1]-data_means[treatment=='control', V1])

sd_neu <- sd_pooled(data[status=='complete' & treatment=='neutral', (q25.score-q12.score)],data[status=='complete' & treatment=='control', (q25.score-q12.score)])

power.t.test(n=29, delta = d_neu, sd =  sd_neu, sig.level = 0.05, power = NULL, type = "two.sample", alternative = "one.sided")

#negative power calc
d_neg <- (data_means[treatment=='negative', V1]-data_means[treatment=='control', V1])

sd_neg <- sd_pooled(data[status=='complete' & treatment=='negative', (q25.score-q12.score)],data[status=='complete' & treatment=='control', (q25.score-q12.score)])

power.t.test(n=29, delta = d_neg, sd =  sd_neg, sig.level = 0.05, power = NULL, type = "two.sample", alternative = "one.sided")


#RI
experiment2 <- function(treat_mean = 100, control_mean=90, n_per_group =10) {
  treat_group   <- rnorm(n=n_per_group, mean=treat_mean,   sd=data_sd[treatment=='neutral', V1])
  control_group <- rnorm(n=29, mean=control_mean, sd=data_sd[treatment=='control', V1])
  t.test(treat_group, control_group)$p.value
}
mean(replicate(100, experiment(treat_mean = data_means[treatment=='neutral', V1], control_mean=data_means[treatment=='control', V1], n_per_group = 30)) < 0.05)
```

**Covariate Balance Check**
```{r echo=FALSE}
# counts
#ggplot(data, aes(x=gender)) + geom_bar()
p1 <- ggplot(data, aes(x=gender, fill = age.demographic)) +
  geom_bar(position="stack")
p1 <- p1 + theme(axis.text.x = element_text(angle = 25, hjust = 1))
p2 <- ggplot(data, aes(x=highest.education, fill = age.demographic)) +
  geom_bar(position="stack")
p2 <- p2 + theme(axis.text.x = element_text(angle = 30, hjust = 1))
p3 <- ggplot(data, aes(x=english.native, fill = age.demographic)) +
  geom_bar()
grid.arrange(p1,p2,p3, ncol=2, top = "Covariate Distributions")
```

```{r, echo= FALSE}
#Attempt at clean summary/stargazer output of initial data

stargazer(d, type="text")

options(na.action = "na.pass")  # so that we keep missing values in the data
X <- model.matrix(~ age.demographic + gender + highest.education - 1, data = d)
X.df <- data.frame(X)  # stargazer only does summary tables of data.frame objects
names(X) <- colnames(X)
stargazer(X.df, type = "text")

summary(d[, c("age.demographic","gender","highest.education", "english.native")])

```

```{r}
bal.tab(treatment ~ age.demographic + highest.education + gender + english.native, data = data, thresholds = c(m = .1))
```

```{r}
install.packages("WeighIt")
m.data <- matchit(treatment ~ highest.education + gender + english.native, data = data[age.demographic=="18-30"])
bal.tab(m.data, thresholds = c(m = .1))

bal.plot(m.data, var.name = "highest.education")
bal.plot(m.data, var.name = "distance", mirror = TRUE, type = "histogram")
```


**Attrition**
```{r}
#Creating subsets
#Simple subset by treatment
data_att_simple = data[, .N, by='treatment']
#Subset by treatment AND complete/attrition/missing data status
data_att <- data[, .N, by=c('treatment', 'status')]
setorder(data_att, cols = 'treatment')
data_att
#Even more subsetting including our age group blocking
data_att_age <- data[, .N, by=c('age.demographic','treatment', 'status')]
setorder(data_att_age, cols = 'age.demographic')
data_att_age
#Including attrition/missing data, equally distributed!
res <- data_att_simple[, chisq.test(N, p=c(1/4,1/4,1/4,1/4))]
res
#Taking into account attrition for entire experiment
res2 <- data_att[status == 'complete', chisq.test(N, p=c(1/4,1/4,1/4,1/4))]
res2
#Now by age group!
#18-30
res3 <- data_att_age[status == 'complete' & age.demographic == '18-30' , chisq.test(N, p=c(1/4,1/4,1/4,1/4))]
res3
#30-40
res4 <- data_att_age[status == 'complete' & age.demographic == '30-40' , chisq.test(N, p=c(1/4,1/4,1/4,1/4))]
res4
#The rest give warning of "Chi-squared approximation may be incorrect"
#Makes sense since we have much less data in these age groups compared to younger than 40
#40-50
res5 <- data_att_age[status == 'complete' & age.demographic == '40-50' , chisq.test(N, p=c(1/4,1/4,1/4,1/4))]
res5
#50-60
res6 <- data_att_age[status == 'complete' & age.demographic == '50-60' , chisq.test(N, p=c(1/4,1/4,1/4,1/4))]
res6
#60+
res7 <- data_att_age[status == 'complete' & age.demographic == '60+' , chisq.test(N, p=c(1/4,1/4,1/4,1/4))]
res7
#Creating attrition table of p values
data_att_p <- data.table(
  age.demographic = c('18-30','30-40', '40-50', '50-60', '60+'),
  p.value = c(res3$p.value,res4$p.value,res5$p.value,res6$p.value,res7$p.value)
)
data_att_p
```

```{r}
p_attrition1 <- ggplot(data, aes(x=status, fill = age.demographic)) +
  geom_bar(position="stack")
p_attrition2 <- ggplot(data, aes(x=status, fill = gender)) +
  geom_bar(position="stack")
grid.arrange(p_attrition1, p_attrition2, top = "Attrition by Age and Gender")
```
```{r}
keycol = c('age.demographic','treatment')
setorderv(data_att_age, keycol)
data_att_age

data_att_gender <- data[, .N, by=c('age.demographic', 'treatment','status','gender')]
data_att_gender[status=='complete']
keycol = c('age.demographic','treatment')
setorderv(data_att_gender, keycol)
data_att_gender[status=='complete']

data_att_edu<- data[, .N, by=c('age.demographic','status','highest.education')]
keycol = c('age.demographic')
setorderv(data_att_edu, keycol)
data_att_edu[status=='complete']

data_att_eng<- data[, .N, by=c('age.demographic','status','english.native')]
setorder(data_att_eng, 'age.demographic')
data_att_eng[status=='complete']
```


```{r}
p_distribution3 <- ggplot(data, aes(x=treatment, fill=age.demographic)) + geom_bar(position="stack") + ggtitle("Treatment Distribution by Age Group")
p_distribution3
```
```{r}

p_distribution4 <- ggplot(data[age.demographic=="18-30",], aes(x=treatment, fill=highest.education)) + geom_bar(position="stack") + ggtitle("Age Group: 18-30") + theme(plot.title = element_text(size=10)) + theme(axis.text.x = element_text(angle = 25, hjust = 1)) + theme(legend.key.size = unit(0.2, "cm"))
p_distribution5 <- ggplot(data[age.demographic=="30-40",], aes(x=treatment, fill=highest.education)) + geom_bar(position="stack") + ggtitle("Age Group: 30-40") + theme(plot.title = element_text(size=10)) + theme(axis.text.x = element_text(angle = 25, hjust = 1)) + theme(legend.key.size = unit(0.2, "cm"))
p_distribution6 <- ggplot(data[age.demographic=="40-50",], aes(x=treatment, fill=highest.education)) + geom_bar(position="stack") + ggtitle("Age Group: 40-50") + theme(plot.title = element_text(size=10)) + theme(axis.text.x = element_text(angle = 25, hjust = 1)) + theme(legend.key.size = unit(0.2, "cm"))
p_distribution7 <- ggplot(data[age.demographic=="50-60"], aes(x=treatment, fill=highest.education)) + geom_bar(position="stack") + ggtitle("Age Group: 50-60") + theme(plot.title = element_text(size=10)) + theme(axis.text.x = element_text(angle = 25, hjust = 1)) + theme(legend.key.size = unit(0.2, "cm"))
p_distribution8 <- ggplot(data[age.demographic=="60+"], aes(x=treatment, fill=highest.education)) + geom_bar(position="stack") + ggtitle("Age Group: 60+") + theme(plot.title = element_text(size=10)) + theme(axis.text.x = element_text(angle = 25, hjust = 1)) + theme(legend.key.size = unit(0.2, "cm"))

grid.arrange(p_distribution4,p_distribution5,p_distribution6,p_distribution7, p_distribution8, ncol=2, top = "Covariate Distributions by Age Group: Highest Education")


```


```{r}
data_att_gender <- data[, .N, by=c('age.demographic', 'status','gender')]
data_att_gender[status=='complete']